
# Configuration du projet Supabase
project_id = "hijgrzabkfynlomhbzij"

# Configuration de l'API Supabase
[api]
port = 54321
schemas = ["public", "storage"]

# Configuration de la base de données PostgreSQL
[db]
port = 54322

# Configuration de l'interface d'administration
[studio]
port = 54324

# Configuration du stockage de fichiers
[storage]
file_size_limit = "50MiB"

# Configuration générale des fonctions Edge
[functions]
port = 54323
serve_dir = "supabase/functions"

# Définition des fonctions Edge individuelles
[[functions.function]]
name = "ensure-storage-buckets"
verify_jwt = true

[[functions.function]]
name = "search"
verify_jwt = false

[[functions.function]]
name = "create-initial-users"
verify_jwt = true

[[functions.function]]
name = "populate-database"
verify_jwt = true
