
project_id = "hijgrzabkfynlomhbzij"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
port = 54323
serve_dir = "supabase/functions"

[functions.ensure-storage-buckets]
verify_jwt = true

[studio]
port = 54324

[storage]
file_size_limit = "50MiB"
