
project_id = "hijgrzabkfynlomhbzij"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

# General function settings
[functions]
port = 54323
serve_dir = "supabase/functions"

# Function-specific configurations
[[functions.function]]
name = "ensure-storage-buckets"
verify_jwt = true

[studio]
port = 54324

[storage]
file_size_limit = "50MiB"
