// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hijgrzabkfynlomhbzij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpamdyemFia2Z5bmxvbWhiemlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzY5NDMsImV4cCI6MjA1ODIxMjk0M30.PR0_0lm94dj-V3_SvOLoo2Dzw2LfWBA_rtDMbGu4UDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);